apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/yourusername/yourrepository.git
    - name: revision
      value: master
  secrets:
    - fieldName: authToken
      secretName: github-secret
      secretKey: token