apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: podman-build
  namespace: tekton
spec:
  workspaces:
    - name: shared-data
    - name: containers
      optional: true
      mountPath: /var/lib/containers
  params: 
    - name: registry 
      description: The target container registry where the image should be pushed 
      default: "<container-registry>" 
    - name: server 
      description: The target registry server 
      default: "<container-server>" 
    - name: repository 
      description: The repository name 
      default: "<container-repository>" 
    - name: tag 
      description: The image tag 
      default: "<container-tag>"
  steps:
    - name: build-image
      image: quay.io/rh_ee_cengleby/podman:0.12
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        podman build -t test-image /workspace/shared-data \

