apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: podman-push
  namespace: tekton
spec:
  workspaces:
    - name: containers
      optional: true
      mountPath: /var/lib/containers
    - name: credentials
      optional: true
      mountPath: /workspace/.docker/
  params: 
    - name: registry 
      description: The target container registry where the image should be pushed 
      default: "<container-registry>" 
    - name: server 
      description: The target registry server 
      default: "<container-server>" 
    - name: repository 
      description: The repository name 
      default: "<container-repository>" 
    - name: tag 
      description: The image tag 
      default: "<container-tag>"
  steps:
    - name: build-image
      image: quay.io/rh_ee_cengleby/podman:0.12
      securityContext:
        privileged: true
        runAsUser: 0
      script: |
        podman tag test-image:latest quay.io/rh_ee_cengleby/apache-livy-3.3.0:latest \
        && podman push quay.io/rh_ee_cengleby/apache-livy-3.3.0:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/workspace/.docker/"
