---
apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata: 
  name: image-pipeline-trigger-template
  namespace: tekton
spec: 
  params: 
    - name: gitrevision 
      description: The git revision sha
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1 
      kind: PipelineRun 
      metadata: 
        name: github-pipeline-run-$(uid)
        namespace: tekton
      spec:
        serviceAccountName: tekton-sa
        pipelineRef: 
          name: example-image-build-pipeline
        params: 
          - name: IMAGE_NAME
            value: "apache-livy-3.3.0" 
          - name: REGISTRY_HOSTNAME
            value: "quay.io" 
          - name: REGISTRY_NAMESPACE
            value: "rh_ee_cengleby" 
          - name: IMAGE_TAG
            value: $(tt.params.gitrevision)
          - name: GITHUB_REPO
            value: 'https://github.com/cengleby86/bc-test-image.git'
          - name: GITHUB_BRANCH
            value: 'main'
        podTemplate:
          securityContext:
            runAsUser: 1001
            fsGroup: 65532
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: clone-output
        - name: containers
          persistentVolumeClaim:
            claimName: varlibcontainers
        - name: credentials
          secret:
            secretName: quay-secret
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: tekton
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
  namespace: tekton
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: github-event-trigger
      bindings:
        - ref: github-binding
          kind: TriggerBinding
      template:
        ref: image-pipeline-trigger-template
        
